# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Metal Shavings
tagline:          Blog
description:      A CNC blog turned repository for writing samples.
url:              https://metalshavings.github.io
baseurl:          /

author:
  name:           ‘Robert Neal Clayton’
  url:            

# Custom vars
version:          3.0.0
