# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Metal Shavings
tagline:          Blog
description:      This was a personal blog about my CNC hobby in 2015, and now includes writing samples as well.
url:              https://metalshavings.github.io
baseurl:          /

author:
  name:           ‘Robert Neal Clayton’
  url:            

# Custom vars
version:          3.0.0
